import { allArtisanTools } from "./types.js";

const ALL_ARTISAN_TOOLS = allArtisanTools();

// Auto-generated by generate-bg-tests.js — do not edit by hand
// Regenerate with: node tests/generate-bg-tests.js

export const backgroundScripts = {
  "Runaway": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Cobbler's Tools",
          "Cook's Utensils",
          "Leatherworker's Tools",
          "Weaver's Tools"
        ],
        "pick": "Cobbler's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Bushcraft"
    ]
  },
  "Broken Home": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Athletics",
          "Acrobatics",
          "History",
          "Nature"
        ],
        "pick": "Athletics",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Open Senses"
    ]
  },
  "Mage's Assistant": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Alchemist's Supplies",
          "Glassblower's Tools",
          "Disguise Kit",
          "Herbalism Kit"
        ],
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Student Of Magic"
    ]
  },
  "Dreams of Doom": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Haunted"
    ]
  },
  "Life-debt": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "History",
          "Insight",
          "Medicine",
          "Nature"
        ],
        "pick": "History",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Driven"
    ]
  },
  "Outcast": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Deception",
          "Persuasion"
        ],
        "pick": "Deception",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Quick Learner"
    ]
  },
  "Avenger": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Athletics",
          "Acrobatics"
        ],
        "pick": "Athletics",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Gaming Set",
          "Musical Instrument"
        ],
        "pick": "Gaming Set",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Tracker"
    ]
  },
  "Exile": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Deception",
          "Intimidation",
          "Performance"
        ],
        "pick": "Deception",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Carpenter's Tools",
          "Tinker's Tools",
          "Weaver's Tools",
          "Woodcarver's Tools"
        ],
        "pick": "Carpenter's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Unpredictable"
    ]
  },
  "Mediator": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "History",
          "Insight",
          "Performance",
          "Persuasion"
        ],
        "pick": "History",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Orator"
    ]
  },
  "Scout": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Carpenter's Tools",
          "Mason's Tools"
        ],
        "pick": "Carpenter's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Adept of the Wild"
    ]
  },
  "Laborer": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Carpenter's Tools",
          "Mason's Tools"
        ],
        "pick": "Carpenter's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Tireless Worker"
    ]
  },
  "Convert": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "History",
          "Religion"
        ],
        "pick": "History",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Calligrapher's Supplies",
          "Cartographer's Tools"
        ],
        "pick": "Calligrapher's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Member of the Church"
    ]
  },
  "Wild": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Carpenter's Tools",
          "Leatherworker's Tools",
          "Potter's Tools",
          "Weaver's Tools"
        ],
        "pick": "Carpenter's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Go to Ground"
    ]
  },
  "Common Folk": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Animal Handling",
          "Athletics",
          "Nature",
          "Survival"
        ],
        "pick": "Animal Handling",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Close to the Earth"
    ]
  },
  "Faithful of Prios": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Brewer's Supplies",
          "Herbalism Kit"
        ],
        "pick": "Brewer's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Shelter of the Faithful"
    ]
  },
  "Houses of Nobility": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "History",
          "Persuasion"
        ],
        "pick": "History",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Calligrapher's Supplies",
          "Any Musical Instrument",
          "Dragonchess Set",
          "Dice Set",
          "Playing Card Set",
          "Three-dragon Ante Set"
        ],
        "pick": "Calligrapher's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Privileged"
    ]
  },
  "Merchant": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Deception",
          "Insight",
          "Persuasion"
        ],
        "pick": "Deception",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Any Artisan's Tool",
          "Herbalism Kit",
          "Any Musical Instrument",
          "Dragonchess Set",
          "Dice Set",
          "Playing Card Set",
          "Three-dragon Ante Set",
          "Navigator's Tools",
          "Vehicles (land)",
          "Vehicles (water)"
        ],
        "pick": "Any Artisan's Tool",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Negotiation"
    ]
  },
  "Refugee": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Nature",
          "Sleight Of Hand",
          "Survival"
        ],
        "pick": "Nature",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Makeshift Tools"
    ]
  },
  "Scholar of Ordo Magica": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Alchemist's Supplies",
          "Painter's Supplies",
          "Tinker's Tools"
        ],
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Practical Knowledge"
    ]
  },
  "Learned in Magic": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Spellbound"
    ]
  },
  "Raised by Common Folk": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Carpenter's Tools",
          "Mason's Tools",
          "Smith's Tools"
        ],
        "pick": "Carpenter's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Unending Labors"
    ]
  },
  "Sellsword": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Athletics",
          "Acrobatics",
          "Deception",
          "Intimidation"
        ],
        "pick": "Athletics",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Carpenter's Tools",
          "Mason's Tools"
        ],
        "pick": "Carpenter's Tools",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Routine Punishment"
    ]
  },
  "Artifact Collector": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Insight",
          "Investigation",
          "Perception"
        ],
        "pick": "Insight",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": ALL_ARTISAN_TOOLS,
        "pick": "Alchemist's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Inspector"
    ]
  },
  "Journey of Discovery": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Skills",
        "confirm": "Use Default"
      },
      {
        "title": "Skill Proficiencies",
        "options": [
          "Arcana",
          "History",
          "Medicine",
          "Religion"
        ],
        "pick": "Arcana",
        "optionSelector": "label span.help"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Tool Proficiencies",
        "options": [
          "Calligrapher's Supplies",
          "Cartographer's Tools",
          "Painter's Supplies",
          "Herbalism Kit"
        ],
        "pick": "Calligrapher's Supplies",
        "optionSelector": "label a"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Cunning Student"
    ]
  },
  "Revenant": {
    "dialogs": [
      {
        "title": "Customize Background"
      },
      {
        "title": "Customize Background: Languages",
        "confirm": "Use Default"
      },
      {
        "title": "Characteristics",
        "confirm": "Skip"
      },
      {
        "title": "Equipment",
        "confirm": "Skip",
        "timeout": 1500
      }
    ],
    "expectedFeats": [
      "Undead"
    ]
  }
};
