// Auto-generated by generate-tests.js — do not edit by hand
// Regenerate with: node tests/generate-tests.js

export const classScripts = {
  "Mystic": {
    "dialogs": [
      {
        "title": "Skill Proficiencies",
        "options": [
          "Arcana",
          "Deception",
          "History",
          "Insight",
          "Investigation",
          "Medicine",
          "Persuasion",
          "Religion"
        ],
        "count": 3,
        "optionSelector": "label span.help"
      }
    ],
    "level1Features": [
      "Cantrips",
      "Leveled Spells",
      "Favored Spells",
      "Approach"
    ],
    "hitDie": 8,
    "casterProgression": "full"
  },
  "Hunter": {
    "dialogs": [
      {
        "title": "Skill Proficiencies",
        "options": [
          "Acrobatics",
          "Athletics",
          "Insight",
          "Investigation",
          "Nature",
          "Perception",
          "Stealth",
          "Survival"
        ],
        "count": 4,
        "optionSelector": "label span.help"
      }
    ],
    "level1Features": [
      "Wilderness Explorer",
      "Approach",
      "Expertise"
    ],
    "hitDie": 8,
    "casterProgression": null
  },
  "Scoundrel": {
    "dialogs": [
      {
        "title": "Skill Proficiencies",
        "options": [
          "Acrobatics",
          "Athletics",
          "Deception",
          "Insight",
          "Intimidation",
          "Investigation",
          "Perception",
          "Performance",
          "Persuasion",
          "Sleight Of Hand",
          "Stealth"
        ],
        "count": 3,
        "optionSelector": "label span.help"
      }
    ],
    "level1Features": [
      "Backstab",
      "Expertise",
      "Approach"
    ],
    "hitDie": 8,
    "casterProgression": null
  },
  "Warrior": {
    "dialogs": [
      {
        "title": "Skill Proficiencies",
        "options": [
          "Acrobatics",
          "Animal Handling",
          "Athletics",
          "History",
          "Insight",
          "Intimidation",
          "Perception",
          "Survival"
        ],
        "count": 3,
        "optionSelector": "label span.help"
      }
    ],
    "level1Features": [
      "Battle Wind",
      "Fighting Style",
      "Approach"
    ],
    "hitDie": 8,
    "casterProgression": null
  },
  "Captain": {
    "dialogs": [
      {
        "title": "Skill Proficiencies",
        "options": [
          "Animal Handling",
          "Athletics",
          "Deception",
          "History",
          "Insight",
          "Intimidation",
          "Perception",
          "Persuasion",
          "Survival"
        ],
        "count": 4,
        "optionSelector": "label span.help"
      }
    ],
    "level1Features": [
      "Fighting Style",
      "Tactical Acumen",
      "Captain Approaches"
    ],
    "hitDie": 8,
    "casterProgression": null
  }
};
