/**
 * Generator script: reads brew JSON files and outputs test scripts for
 * races, classes, and subclasses.
 *
 * Usage: node tests/generate-tests.js
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const brewDir = join(__dirname, "..", "brew");

function readBrew(subdir, filename) {
  return JSON.parse(readFileSync(join(brewDir, subdir, filename), "utf8"));
}

function titleCase(str) {
  return str
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

const ABILITY_NAMES = {
  str: "Strength",
  dex: "Dexterity",
  con: "Constitution",
  int: "Intelligence",
  wis: "Wisdom",
  cha: "Charisma",
};

const LANG_MAP = {
  common: "Common",
  elvish: "Elvish",
  undercommon: "Undercommon",
  dwarvish: "Dwarvish",
  "Troll|RuinsOfSymbaroumR": "Troll",
};

// ============================================================
// RACES
// ============================================================
function generateRaceScripts() {
  const brew = readBrew("race", "Awarenet; Ruins of Symbaroum (Race).json");

  const scripts = {};

  for (const race of brew.race) {
    const dialogs = [];
    const ab = race.ability?.[0];

    // 1) Ability Score Increase — if there's a choose
    if (ab?.choose) {
      dialogs.push({
        title: "Ability Score Increase",
        options: ab.choose.from.map((a) => ABILITY_NAMES[a]),
        pick: ABILITY_NAMES[ab.choose.from[0]],
        optionSelector: "label span.help",
      });
    }

    // 2) Language Proficiencies — if there's a choose
    const lp = race.languageProficiencies?.[0];
    if (lp?.choose) {
      dialogs.push({
        title: "Language Proficiencies",
        options: lp.choose.from.map((l) => LANG_MAP[l] || titleCase(l)),
        pick: LANG_MAP[lp.choose.from[0]] || titleCase(lp.choose.from[0]),
        count: lp.choose.count,
        optionSelector: "label a",
      });
    }
    if (lp?.anyStandard) {
      dialogs.push({
        title: "Language Proficiencies",
        pickAny: lp.anyStandard,
      });
    }

    // Detect subraces
    const subraces = (brew.subrace || []).filter(
      (sr) => sr.raceName === race.name,
    );

    scripts[race.name] = {
      dialogs,
      subraces: subraces.map((sr) => sr.name),
    };
  }

  return scripts;
}

// ============================================================
// CLASSES
// ============================================================
function generateClassScripts() {
  const brew = readBrew("class", "Awarenet; Ruins of Symbaroum (Class).json");

  const scripts = {};

  for (const cls of brew.class) {
    const dialogs = [];
    const skills = cls.startingProficiencies?.skills?.[0];

    // Skill proficiency choices
    if (skills?.choose) {
      dialogs.push({
        title: "Skill Proficiencies",
        options: skills.choose.from.map((s) => titleCase(s)),
        count: skills.choose.count,
        optionSelector: "label span.help",
      });
    }

    // Extract level-1 class feature names from classFeatures
    const level1Features = (cls.classFeatures || [])
      .map((f) => (typeof f === "string" ? f : f.classFeature))
      .filter((f) => f && f.endsWith("|1"))
      .map((f) => f.split("|")[0]);

    scripts[cls.name] = {
      dialogs,
      level1Features,
      hitDie: cls.hd?.faces,
      casterProgression: cls.casterProgression || null,
    };
  }

  return scripts;
}

// ============================================================
// SUBCLASSES
// ============================================================
function generateSubclassScripts() {
  const brew = readBrew(
    "subclass",
    "Awarenet; Ruins of Symbaroum (Subclass).json",
  );

  const scripts = {};

  for (const sc of brew.subclass) {
    // Extract level-1 subclass feature names
    const level1Features = (sc.subclassFeatures || [])
      .filter((f) => typeof f === "string" && f.endsWith("|1"))
      .map((f) => f.split("|")[0]);

    scripts[sc.name] = {
      className: sc.className,
      classSource: sc.classSource,
      level1Features,
      spellcastingAbility: sc.spellcastingAbility || null,
    };
  }

  return scripts;
}

// ============================================================
// Generate all outputs
// ============================================================
function writeModule(filename, varName, data, imports = []) {
  const lines = [];
  if (imports.length) {
    lines.push(...imports, "");
  }
  lines.push(
    "// Auto-generated by generate-tests.js — do not edit by hand",
    "// Regenerate with: node tests/generate-tests.js",
    "",
    `export const ${varName} = ${JSON.stringify(data, null, 2)};`,
    "",
  );
  const outPath = join(__dirname, filename);
  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${filename} (${Object.keys(data).length} entries)`);
}

const races = generateRaceScripts();
const classes = generateClassScripts();
const subclasses = generateSubclassScripts();

writeModule("race-scripts.js", "raceScripts", races);
writeModule("class-scripts.js", "classScripts", classes);
writeModule("subclass-scripts.js", "subclassScripts", subclasses);
