// Auto-generated by generate-tests.js — do not edit by hand
// Regenerate with: node tests/generate-tests.js

export const raceScripts = {
  "Abductee": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Constitution",
          "Intelligence",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      }
    ],
    "subraces": []
  },
  "Changeling": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Dexterity",
          "Constitution",
          "Intelligence",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "options": [
          "Elvish",
          "Undercommon",
          "Common"
        ],
        "pick": "Elvish",
        "count": 2,
        "optionSelector": "label a"
      }
    ],
    "subraces": []
  },
  "Dwarf": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Dexterity",
          "Constitution",
          "Wisdom",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "options": [
          "Common",
          "Undercommon",
          "Troll",
          "Elvish"
        ],
        "pick": "Common",
        "count": 2,
        "optionSelector": "label a"
      }
    ],
    "subraces": []
  },
  "Elf": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Dexterity",
          "Constitution",
          "Intelligence",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "options": [
          "Troll",
          "Common",
          "Undercommon"
        ],
        "pick": "Troll",
        "count": 2,
        "optionSelector": "label a"
      }
    ],
    "subraces": []
  },
  "Goblin": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Constitution",
          "Intelligence",
          "Wisdom",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "options": [
          "Troll",
          "Elvish"
        ],
        "pick": "Troll",
        "count": 1,
        "optionSelector": "label a"
      }
    ],
    "subraces": []
  },
  "Ogre": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Dexterity",
          "Intelligence",
          "Wisdom",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "pickAny": 1
      }
    ],
    "subraces": []
  },
  "Troll": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Dexterity",
          "Constitution",
          "Intelligence",
          "Wisdom",
          "Charisma"
        ],
        "pick": "Dexterity",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "options": [
          "Elvish",
          "Common",
          "Undercommon"
        ],
        "pick": "Elvish",
        "count": 2,
        "optionSelector": "label a"
      }
    ],
    "subraces": []
  },
  "Undead": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Dexterity",
          "Intelligence",
          "Wisdom",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "pickAny": 1
      }
    ],
    "subraces": []
  },
  "Rebirthed": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Strength",
          "Dexterity",
          "Intelligence",
          "Wisdom",
          "Charisma"
        ],
        "pick": "Strength",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "pickAny": 1
      }
    ],
    "subraces": []
  },
  "Human": {
    "dialogs": [
      {
        "title": "Ability Score Increase",
        "options": [
          "Dexterity",
          "Constitution",
          "Charisma"
        ],
        "pick": "Dexterity",
        "optionSelector": "label span.help"
      },
      {
        "title": "Language Proficiencies",
        "pickAny": 1
      }
    ],
    "subraces": [
      "Ambrian",
      "Barbarian"
    ]
  }
};
