// Auto-generated by generate-tests.js — do not edit by hand
// Regenerate with: node tests/generate-tests.js

export const subclassScripts = {
  "Artifact Crafter": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Artifact Crafter",
      "Titles",
      "Corruption",
      "Spellcasting",
      "Talisman Crafter"
    ],
    "spellcastingAbility": "wis"
  },
  "Self-taught": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Self-taught",
      "Titles",
      "Corruption",
      "Spellcasting",
      "Boundless Magic"
    ],
    "spellcastingAbility": "int"
  },
  "Sorcerer": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Sorcerer",
      "Titles",
      "Corruption",
      "Spellcasting",
      "The Darkened Path"
    ],
    "spellcastingAbility": "cha"
  },
  "Staff Mage": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Spellcasting",
      "Staff Mage",
      "Titles",
      "Corruption",
      "Bonus Spell",
      "Staff Fighting"
    ],
    "spellcastingAbility": "int"
  },
  "Symbolist": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Symbolist",
      "Titles",
      "Corruption",
      "Spellcasting",
      "Bonus Spell"
    ],
    "spellcastingAbility": "int"
  },
  "Theurg": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Theurg",
      "The Titles of Theurgy",
      "Corruption",
      "Spellcasting",
      "Bonus Spell"
    ],
    "spellcastingAbility": "wis"
  },
  "Troll Singer": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Troll Singer",
      "Titles",
      "Corruption",
      "Spellcasting",
      "Songs of the Dawn"
    ],
    "spellcastingAbility": "cha"
  },
  "Witch": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Witch",
      "Titles",
      "Corruption",
      "Spellcasting",
      "A Chosen Path",
      "Nature's Bounty"
    ],
    "spellcastingAbility": "wis"
  },
  "Wizard": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Wizard",
      "The Titles of Ordo Magica",
      "Corruption",
      "Spellcasting",
      "Bonus Spells"
    ],
    "spellcastingAbility": "int"
  },
  "Merchant Master": {
    "className": "Captain",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Assessment"
    ],
    "spellcastingAbility": null
  },
  "Officer": {
    "className": "Captain",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Army Brat"
    ],
    "spellcastingAbility": null
  },
  "Outlaw": {
    "className": "Captain",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Hard to Find",
      "Secret Signs"
    ],
    "spellcastingAbility": null
  },
  "Poet-warrior": {
    "className": "Captain",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Reflection"
    ],
    "spellcastingAbility": null
  },
  "Bounty Hunter": {
    "className": "Hunter",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Sturdy Holds"
    ],
    "spellcastingAbility": null
  },
  "Ironsworn": {
    "className": "Hunter",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Agile Combat"
    ],
    "spellcastingAbility": null
  },
  "Monster Hunter": {
    "className": "Hunter",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "The Bigger They Are..."
    ],
    "spellcastingAbility": null
  },
  "Witch Hunter": {
    "className": "Hunter",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Deep Knowledge"
    ],
    "spellcastingAbility": null
  },
  "Explorer": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Precise Shot",
      "Wilderness-master"
    ],
    "spellcastingAbility": "cha"
  },
  "Former Cultist": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Channeling",
      "The Darkened Path"
    ],
    "spellcastingAbility": "cha"
  },
  "Guild Thief": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Speciality",
      "Blade Work"
    ],
    "spellcastingAbility": null
  },
  "Sapper": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Blacksmith",
      "Firetube"
    ],
    "spellcastingAbility": null
  },
  "Spy": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Network of Contacts",
      "Dissembling Words",
      "Feint"
    ],
    "spellcastingAbility": null
  },
  "Thug": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Twin Attack"
    ],
    "spellcastingAbility": null
  },
  "Treasure-hunter": {
    "className": "Scoundrel",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Steel Throw",
      "Tactician"
    ],
    "spellcastingAbility": null
  },
  "Berserker": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Rage"
    ],
    "spellcastingAbility": null
  },
  "Duelist": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Feint"
    ],
    "spellcastingAbility": null
  },
  "Knight": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Bodyguard"
    ],
    "spellcastingAbility": null
  },
  "Rune Smith": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Blacksmith"
    ],
    "spellcastingAbility": null
  },
  "Templar": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Armored Mystic"
    ],
    "spellcastingAbility": "wis"
  },
  "Tattooed Fighter": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Unarmored Defense",
      "Rune Tattoos"
    ],
    "spellcastingAbility": null
  },
  "Weapon Master": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Fighting Style Mastery"
    ],
    "spellcastingAbility": null
  },
  "Wrathguard": {
    "className": "Warrior",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Wrathful Fury"
    ],
    "spellcastingAbility": null
  },
  "Blood Mage": {
    "className": "Mystic",
    "classSource": "RuinsOfSymbaroumC",
    "level1Features": [
      "Blood Mage",
      "Titles",
      "Corruption",
      "Bonus Spell"
    ],
    "spellcastingAbility": "int"
  }
};
