export const ArtisanTool = Object.freeze({
  ALCHEMIST: "Alchemist's Supplies",
  BREWER: "Brewer's Supplies",
  CALLIGRAPHER: "Calligrapher's Supplies",
  CARPENTER: "Carpenter's Tools",
  CARTOGRAPHER: "Cartographer's Tools",
  COBBLER: "Cobbler's Tools",
  COOK: "Cook's Utensils",
  GLASSBLOWER: "Glassblower's Tools",
  JEWELER: "Jeweler's Tools",
  LEATHERWORKER: "Leatherworker's Tools",
  MASON: "Mason's Tools",
  PAINTER: "Painter's Supplies",
  POTTER: "Potter's Tools",
  SMITH: "Smith's Tools",
  TINKER: "Tinker's Tools",
  WEAVER: "Weaver's Tools",
  WOODCARVER: "Woodcarver's Tools",
});

export const allArtisanTools = () => Object.values(ArtisanTool);

export const ImportType = Object.freeze({
  ACTIONS: "Actions",
  ADVENTURES: "Adventures",
  BACKGROUNDS: "Backgrounds",
  BOOKS: "Books",
  CHARACTER_CREATION: "Character Creation Options",
  CLASSES: "Classes & Subclasses",
  CLASS_FEATURES: "Class & Subclass Features",
  CONDITIONS: "Conditions & Diseases",
  CREATURES: "Creatures",
  CREATURE_FEATURES: "Creature Features",
  CULTS: "Cults & Supernatural Boons",
  DECKS: "Decks",
  DEITIES: "Deities",
  FEATS: "Feats",
  FACILITIES: "Facilities",
  HAZARDS: "Hazards",
  ITEMS: "Items",
  LANGUAGES: "Languages",
  MAPS: "Maps",
  OBJECTS: "Objects",
  OPTIONS_FEATURES: "Other Options & Features",
  PSIONICS: "Psionics",
  RECIPES: "Recipes",
  RULES: "Rules",
  SPECIES: "Species & Subspecies",
  SPELLS: "Spells",
  GIFTS_REWARDS: "Supernatural Gifts & Rewards",
  TABLES: "Tables",
  TRAPS: "Traps",
  VEHICLES: "Vehicles",
  VEHICLE_UPGRADES: "Vehicle Upgrades",
});

export const ItemType = Object.freeze({
  BACKGROUND: "background",
  CLASS: "class",
  CONSUMABLE: "consumable",
  CONTAINER: "container",
  EQUIPMENT: "equipment",
  FACILITY: "facility",
  FEAT: "feat",
  LOOT: "loot",
  SPELL: "spell",
  SUBCLASS: "subclass",
  TOOL: "tool",
  WEAPON: "weapon",
});
